### ISSUE TITLE
На Mac OS при использовании docker-machine появляется проблема

### ISSUE THREAD

**Issue by tupikoff** [covex-nn/docker-workflow-symfony#1]
На Mac OS при использовании docker-machine появляется проблема с доступами к файлам, описанная здесь: https://github.com/boot2docker/boot2docker/issues/581
Проявляется в том, что владелец и права на файлы не меняются, на примонтированных nfs томах, Symfony не может запуститься (не может писать в /var/cache/dev/)
Решается: https://github.com/adlogix/docker-machine-nfs:
1. Устанавливаем: brew install docker-machine-nfs
2. Запускаем: docker-machine-nfs default

Спасибо за ваше решение.
Будет здорово, если добавите это инфо про macos, может кому то пригодится

**Comment by covex-nn** [comment]
@tupikoff я рад, что моё решение пригодилось =)
К сожалению, у меня нет возможности протестировать работу `docker-machine` под Mac OS.

Под Windows тоже есть проблема с записью файлов в `var/sessions` - файлы не записываются, точнее они создаются и остаются пустыми. Директорию пришлось перенести внутрь контейнера для окружения разработчика. Наверное стоит сделать это для всей директории `var`.

**Comment by covex-nn** [comment]
См. https://github.com/covex-nn/docker-workflow-symfony/pull/3
